services:
  gil-bot-backend:
    image: registry.yosefbyd.com/gil-bot-backend:latest
    container_name: gil-bot-backend
    env_file:
      - .gil-bot-backend.env
    depends_on:
      - mongo
    networks:
      - proxy
    environment:
      - DEBUG=True
      - PYTHONUNBUFFERED=1 # Ensures logs aren't buffered
    labels:
      - traefik.enable=true
      - traefik.http.services.gil-bot-backend.loadbalancer.server.port=8000
      - traefik.http.routers.gil-bot-backend.rule=Host(`gil-bot-api.yosefbyd.com`)
      - traefik.docker.network=proxy

  mongo:
    image: mongo:latest
    container_name: gil-bot-mongo
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: ${MONGODB_DB_NAME:-gil_whatsapp_bot}
      MONGO_INITDB_USERNAME: ${MONGO_USER:-user}
      MONGO_INITDB_PASSWORD: ${MONGO_PASSWORD:-pass}
    networks:
      - proxy

  gil-bot-frontend:
    image: registry.yosefbyd.com/gil-bot-frontend:latest
    container_name: gil-bot-frontend
    depends_on:
      - gil-bot-backend
    networks:
      - proxy
    environment:
      - REACT_APP_API_BASE_URL=https://gil-bot-api.yosefbyd.com
    labels:
      - traefik.enable=true
      - traefik.http.services.gil-bot-frontend.loadbalancer.server.port=3000
      - traefik.http.routers.gil-bot-frontend.rule=Host(`gil-bot.yosefbyd.com`)
      - traefik.docker.network=proxy

volumes:
  mongo_data:

networks:
  proxy:
    external: true