services:
  backend:
    image: registry.yosefbyd.com/gil-bot-backend:latest
    container_name: gil-bot-backend
    volumes:
      - ./backend/app:/app/app # Mount local code for development changes
    depends_on:
      - mongo
    networks:
      - proxy
      - gil-network
    environment:
      - DEBUG=True
      - PYTHONUNBUFFERED=1 # Ensures logs aren't buffered
    labels:
      - traefik.enable=true
      - traefik.http.services.gil-bot-backend.loadbalancer.server.port=8000
      - traefik.http.routers.gil-bot-backend.rule=Host(`gil-bot-api.yosefbyd.com`)
      - traefik.docker.network=proxy

  mongo:
    image: mongo:latest
    container_name: gil-bot-mongo
    volumes:
      - mongo_data:/data/db
    environment:
      # Variables to create the specific application user and database
      MONGO_INITDB_DATABASE: ${MONGODB_DB_NAME:-gil_whatsapp_bot}
      MONGO_INITDB_USERNAME: ${MONGO_USER:-user}
      MONGO_INITDB_PASSWORD: ${MONGO_PASSWORD:-pass}
    networks:
      - gil-network

  frontend:
    image: registry.yosefbyd.com/gil-bot-frontend:latest
    container_name: gil-bot-frontend
    volumes:
      - ./frontend/src:/app/src
    depends_on:
      - backend
    networks:
      - proxy
      - gil-network
    labels:
      - traefik.enable=true
      - traefik.http.services.gil-bot-frontend.loadbalancer.server.port=3000
      - traefik.http.routers.gil-bot-frontend.rule=Host(`gil-bot.yosefbyd.com`)
      - traefik.docker.network=proxy

volumes:
  mongo_data:


networks:
  gil-network:
    driver: bridge
  proxy:
    external: true
