services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: gil-bot-backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app # Mount local code for development changes
    depends_on:
      - mongo
    networks:
      - gil-network
    environment:
      - DEBUG=True
      - PYTHONUNBUFFERED=1 # Ensures logs aren't buffered

  mongo:
    image: mongo:latest
    container_name: gil-bot-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: ${MONGODB_DB_NAME:-gil_whatsapp_bot}
      MONGO_INITDB_USERNAME: ${MONGO_USER:-user} # Use a distinct variable name if needed
      MONGO_INITDB_PASSWORD: ${MONGO_PASSWORD:-pass} # Use a distinct variable name if needed
    networks:
      - gil-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: gil-bot-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:8000
    volumes:
      - ./frontend/src:/app/src
    depends_on:
      - backend
    networks:
      - gil-network
volumes:
  mongo_data:


networks:
  gil-network:
    driver: bridge
