name: Build and Deploy

on:
  push:
    branches: [main]

jobs:
  build-push:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      
      - uses: docker/setup-buildx-action@v3
      
      - name: Test registry connectivity
        run: |
          curl -I https://registry.yosefbyd.com/v2/ || echo "Registry test failed, but continuing..."
          
      - uses: docker/login-action@v3
        with:
          registry: registry.yosefbyd.com
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASS }}
          
      - name: Build and push unified image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            registry.yosefbyd.com/gil-bot:latest
            registry.yosefbyd.com/gil-bot:${{ github.sha }} 