name: Build & Push Docker Images
# Expain each line with comments
on:
  push:
    branches: [main]
    paths: # this is a list of paths that will trigger the workflow - any change in the backend, frontend or github workflows will trigger the workflow structured below
      - 'backend/**'
      - 'frontend/**'
      - '.github/workflows/**'

jobs:
  build: # this is the job that will build the docker images
    runs-on: ubuntu-latest

    strategy: # this is a matrix strategy - it will build the docker images for the backend and frontend then push them to the registry hosted on our server at registry.yosefbyd.com
      matrix:
        include:
          - app: backend # this is the name of the app that will be built - the name will be used to tag the image at the registry
            image: registry.yosefbyd.com/gil-bot-backend
            context: ./backend
            dockerfile: ./backend/Dockerfile

          - app: frontend # this is the name of the app that will be built - the name will be used to tag the image at the registry
            image: registry.yosefbyd.com/gil-bot-frontend
            context: ./frontend
            dockerfile: ./frontend/Dockerfile

    steps:
      - name: Checkout repository # this is the step that will checkout the repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx # this is the step that will set up the docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to private registry
        uses: docker/login-action@v3
        with:
          registry: registry.yosefbyd.com
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASS }}

      - name: Build & Push ${{ matrix.app }}
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.context }}
          file:    ${{ matrix.dockerfile }}
          push:    true
          no-cache: true
          cache-from: type=registry,ref=${{ matrix.image }}:buildcache
          cache-to:   type=registry,ref=${{ matrix.image }}:buildcache,mode=max
          tags: |
            ${{ matrix.image }}:latest
            ${{ matrix.image }}:${{ github.sha }}
          platforms: linux/amd64
